import AuthRoutes from "./authRoutes";
import UserRoutes from "./userRoutes";
import hostRoutes from "./hostRoutes";
import coinsPriceRoutes from "./coinPriceRoutes";
import callRoutes from "./callRoutes";
import chatRoutes from "./chatRoutes";
import frameRoute from "./frameRoutes";
import avatarRoute from "./avatarRoutes";
import adminRoutes from "./adminRoutes";
import paymentRoutes from "./paymentRoutes";
import kycRoutes from "./kycRoutes";
import withdrawalRoutes from "./withdrawalRoutes";
import giftRoutes from "./giftRoutes";
import helpRoutes from "./helpRoutes";
import UploadRoutes from "./uploadRoutes";
import notificationRoutes from "./notificationRoutes";
import upiRoutes from "./upiRoutes";
import publicRoutes from "./publicRoutes";
import emsRoutes from "./emsRoutes";
import recruitmentRoutes from "./recruitmentRoutes";
import sellerRoutes from "./sellerRoutes";
import voiceClubRoutes from "./voiceClubRoutes";

export { AuthRoutes, UserRoutes, hostRoutes, coinsPriceRoutes, callRoutes, chatRoutes, avatarRoute, frameRoute, adminRoutes, paymentRoutes, kycRoutes, withdrawalRoutes, giftRoutes, helpRoutes, UploadRoutes, notificationRoutes, upiRoutes, publicRoutes, emsRoutes, recruitmentRoutes, sellerRoutes, voiceClubRoutes };