// user.interface.ts
import { Document, Types } from "mongoose";
import { AuthType, Gender, UserRole } from "../constants/user";


export interface UserInterface extends Document {
  userId: number;
  name?: string;
  email?: string;
  phoneNumber?: string;
  gender?: Gender;
  fcmToken?: string;
  bio?: string;
  hobbies?: string[];
  emailVerified?: boolean;
  phoneVerified?: boolean;
  password?: string;
  role?: UserRole;
  authType?: AuthType;
  coins?: number;
  diamonds?: number;
  image?: string;
  createdBy?: Types.ObjectId;
  isDeleted?: boolean;
  isOnline?: boolean;
  isBlocked?: boolean;
  lastOnline?: Date;
  lastActiveAt?: Date;
  device: {
    createdDeviceId?: string;
    currentDeviceId?: string;
    loggedInDeviceIds: string[];
    ipAddress?: string;
  };
  ipAddress?: string;
  lastIp?: string;
  googleId?: string;
  language?: string[];
  country?: { name?: string; code?: string; flag?: string };
  age?: number;
  frameId?: string;
  refreshToken?: string;
  activeToken?: string;
  audio?: string;
  isUserName?: boolean;
  userName?: string;
  isActive?: boolean;
  isBusy?: boolean;
  meethiId?: string;
  blockedUsers?: Types.ObjectId[];
  level?: number;
  employeeCode?: string;
  parentId?: Types.ObjectId;
  referredBy?: any;
  referralCode?: string;
  profileCompleted?: boolean;
  welcomeRewardClaimed?: boolean;
  referralClaimed?: boolean;
  referralLink?: string;
  referrerId?: string;
  referrerRole?: string;
  referrerCode?: string;
  totalReferrals?: number;
  activeReferrals?: number;
  pendingReferrals?: number;
  approvedReferrals?: number;
  rejectedReferrals?: number;
  monthlyReferrals?: number;
  todayReferrals?: number;
  lastReferralAt?: Date;
  totalClicks?: number;
  totalQrScans?: number;
  conversionRate?: string;
  parentUserId?: string;
  rootReferralId?: string;
  hierarchyPath?: string;
  referralOwnerId?: string;
  referralOwnerRole?: string;
  rootOwnerId?: Types.ObjectId | string;
  rootOperatorId?: Types.ObjectId | string;
  networkId?: string;
  treeDepth?: number;
  createdFromReferral?: boolean;
  isRootNode?: boolean;
  childrenCount?: number;
  activeChildren?: number;
  pendingChildren?: number;
  approvedChildren?: number;
  totalNetworkUsers?: number;
  lastHierarchyUpdate?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  documents?: string[];
  sourceForm?: string;
  parentRole?: string;
  createdByRole?: string;
  ownerId?: Types.ObjectId;
  operatorId?: Types.ObjectId;
  superAdminId?: Types.ObjectId;
  adminId?: Types.ObjectId;
  agencyId?: Types.ObjectId;
  specialCode?: string;
  orgId?: Types.ObjectId;
  branchId?: Types.ObjectId;
  departmentId?: Types.ObjectId;
  teamId?: Types.ObjectId;
  mustChangePassword?: boolean;
  loginUrl?: string;
  lastLogin?: Date;
  emsRequestId?: Types.ObjectId;
  status?: string;
  deletedBy?: Types.ObjectId;
  deletedAt?: Date;
  deleteReason?: string;
  faceVerificationStatus?: 'NOT_SUBMITTED' | 'PENDING' | 'APPROVED' | 'REJECTED';
  kycVerificationStatus?: 'NOT_SUBMITTED' | 'PENDING' | 'APPROVED' | 'REJECTED';
  faceVerifiedAt?: Date;
  kycVerifiedAt?: Date;
  chatMuteUntil?: Date;
  chatMuteReason?: string;
  chatMuteViolationCount?: number;
  accountReviewRequired?: boolean;
  accountReviewReason?: string;
  lastEscalationAction?: string;
  lastEscalatedAt?: Date;
  moderationRiskScore?: number;
  moderationRiskLevel?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  moderationLastViolationAt?: Date;
  lastLoginIp?: string;
  deviceId?: string;
}
